const SHOP_TYPES = {
  FETCHING_COLLECIONS_START: "FETCHING_COLLECION_START",
  FETCHING_SUGGESTED_COLLECIONS_START: "FETCHING_COLLECION_START",
  FETCHING_CATEGORIES_START: "FETCHING_CATEGORIES_START",
  FETCHING_COLLECTIONS_SUCCESS: "FETCHING_COLLECTIONS_SUCCESS",
  FETCHING_SUGGESTED_COLLECTIONS_SUCCESS:
    "FETCHING_SUGGESTED_COLLECTIONS_SUCCESS",
  FETCHING_CATEGORIES_SUCCESS: "FETCHING_CATEGORIES_SUCCESS",
  FETCHING_COLLECTIONS_FAILED: "FETCHING_COLLECTIONS_FAILED",
};

export default SHOP_TYPES;
