const PRODUCT_TYPES = {
    FETCHING_PRODUCTS_START : 'FETCHING_PRODUCTS_START',
    FETCHING_PRODUCTS_SUCCESS: 'FETCHING_PRODUCTS_SUCCESS',
    FETCHING_PRODUCTS_FAILED : 'FETCHING_PRODUCTS_FAILED',
    UPLOADING_PRODUCTS_START : 'UPLOADING_PRODUCTS_START',
    UPLOADING_PRODUCTS_SUCCESS : 'UPLOADING_PRODUCTS_SUCCESS',
    UPLOADING_PRODUCTS_FAILED : 'UPLOADING_PRODUCTS_FAILED',

}

export default PRODUCT_TYPES;
