const PRENDAS_TYPES = {
    FETCHING_START : 'FETCHING_PRODUCTS_START',
    FETCHING_TALLAS_SUCCESS: 'FETCHING_PRODUCTS_SUCCESS',
    FETCHING_FAILED : 'FETCHING_PRODUCTS_FAILED',
    

}

export default  PRENDAS_TYPES;
